name: update-csv

on:
  schedule:
    - cron: 0 19 * * *
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Use the version of Python that matches your project's requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Update CSV and write to backup file
        run: |
          python entrypoint.py csv
        env:
          FIFAGUTTA_SECRET_KEY: ${{ secrets.FIFAGUTTA_SECRET_KEY }}
          FIFAGUTTA_PASSWORDS_JSON: ${{ secrets.FIFAGUTTA_PASSWORDS_JSON }}
          FIFAGUTTA_UNAME_SHORT_JSON: ${{ secrets.FIFAGUTTA_UNAME_SHORT_JSON }}
          FIFAGUTTA_DATABASE_URL: ${{ secrets.FIFAGUTTA_DATABASE_URL }}

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/2025.csv
          git add data/backup/*
          git pull origin main
          git commit -m 'Updated data with latest standings' || echo 'No changes to commit'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
