name: update-schedule

on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Use the version of Python that matches your project's requirements

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Update Schedule 
        run: |
          python entrypoint.py 
        env:
          FIFAGUTTA_SECRET_KEY: ${{ secrets.FIFAGUTTA_SECRET_KEY }}
          FIFAGUTTA_PASSWORDS_JSON: ${{ secrets.FIFAGUTTA_PASSWORDS_JSON }}
          FIFAGUTTA_UNAME_SHORT_JSON: ${{ secrets.FIFAGUTTA_UNAME_SHORT_JSON }}
          FIFAGUTTA_DATABASE_URL: ${{ secrets.FIFAGUTTA_DATABASE_URL }}